/**
 * Expands the Edge Editor's published `edgeDefinitions` into the
 * `edgeTable` shape — `{ intrinsic, edges, cxtEdges }` per entityType.
 * Wired into the live `entityTemplate` build (see ./index.js).
 *
 * Keying rule: every entry is keyed by its full storage `path` (unique within an
 * entity+partition). The legacy flattener keyed by the last path segment (the range
 * type), but that cannot represent two predicates to the same range — e.g. a nested
 * Context needs both edges.hasCxt.Context and edges.cxtFor.Context. Path keying avoids
 * that collision.
 *
 * Per-range vs per-property entries:
 *   - When the path embeds {range} (placement 'edges', or a pathTemplate with
 *     {range}) one entry is emitted per (domain, range), allowed = [range].
 *   - When the path is constant for the group (intrinsic property) one entry is
 *     emitted per domain, allowed = the whole group's range list.
 *
 * cxtEdges are generated by the second pass below, projected from the forward edges.
 *
 * Each entry carries pre-decomposed path fields (`bucket`, `pathSegments`,
 * `containerSegments`, `relativePath`) so consumers never do string surgery on `path`,
 * and `maxItems` derived from the JSON Schema (see ../schemaFacts.js). Note `type` is
 * the *storage shape* ('array' | 'object') — it is NOT a cardinality cap. In v3.0 every
 * edge is stored as an array, so `maxItems` is the only thing that says "at most one".
 *
 * @module buildEdgeTable
 */

import { tentativeRdf } from './rdfTemplates.js';
import { maxItemsIndex } from './schemaIndex.js';

/**
 * Resolve an inverse predicate NAME to the inverse PATH on the target entity.
 * `originDomain` (the source type of the forward edge) becomes the last segment
 * of an `edges.<inv>.<originDomain>` reverse path.
 *
 * @param {Object} definitions - The edge definitions the inverse is looked up in
 * @param {string|null} invName - The inverse predicate name
 * @param {string} originDomain - The source type of the forward edge
 * @returns {string|null} The inverse storage path
 */
const resolveInversePath = (definitions, invName, originDomain) => {
    if (!invName) return null;
    const invDef = definitions[invName];
    const invPlacement = invDef ? invDef.placement || 'edges' : 'edges';
    if (invPlacement === 'edges') return `edges.${invName}.${originDomain}`;
    // intrinsic inverse: the reverse reference lives at a named property
    return (invDef && invDef.path) || invName;
};

/**
 * The inverse as an edge rather than a name: where the reverse reference is written on the target,
 * decomposed the same way a forward path is.
 *
 * A name alone cannot say this. `memberOf` inverts to the intrinsic property `Member`, and
 * `realizedBy` inverts to `RealizationOf` in general but to `usedBy` from Task and Participant, so
 * a reader given only the name has to guess a bucket and cannot see the override at all. Consumers
 * that write the reverse edge — fMam does, on every save — need the place, not the word.
 *
 * `maxItems` is the cap on the slot the reverse goes into, which is a fact about the TARGET's row
 * rather than this one. It is known only once the target's table exists, so it arrives in the third
 * pass below; until then the inverse carries the place but not the cap.
 *
 * @param {string|null} inversePath - The resolved inverse path, or null where there is no inverse
 * @param {number|undefined} [maxItems] - The cap on the target's slot, from its own row
 * @returns {{predicate: string, bucket: string, path: string, pathSegments: string[],
 *   containerSegments: string[], relativePath: string, maxItems: (number|undefined)}|null}
 */
const inverseEdgeOf = ((inversePath, maxItems) => {
    if (!inversePath) return null;
    const bucket = inversePath.startsWith('edges.') ? 'edges' : 'intrinsic';
    const decomposed = decomposePath(inversePath, bucket);
    return {
        // An edges path is named by its verb; an intrinsic one by the property it ends in.
        predicate: bucket === 'edges' ? decomposed.pathSegments[1] : decomposed.pathSegments.at(-1),
        path: inversePath,
        ...decomposed,
        maxItems,
    };
});

/**
 * How a reference is stored on the source entity. Every v3.0 edge is an array — intrinsic or not —
 * so this is a constant, not something the publication has to state. It is **not** a cardinality cap:
 * `maxItems` is. `insertEdge` dispatches on it with no default, so a row without one writes nothing
 * and says nothing about it.
 */
const STORAGE_TYPE = 'array';

/** The three partitions every entityType's table carries. */
const PARTITION_NAMES = ['intrinsic', 'edges', 'cxtEdges'];

const pathDependsOnRange = (placement, template) =>
    placement === 'edges' || (!!template && template.includes('{range}'));

/**
 * Pre-decompose a storage path so consumers never split/slice it themselves.
 *
 * The final segment is where the reference itself sits — the range type for an
 * `edges.{predicate}.{range}` path, or the property name for an intrinsic one — so
 * `containerSegments` (everything before it) is the object path a writer must create
 * before placing the value.
 *
 * @param {string} path - Full storage path, e.g. `edges.hasCxt.Context` or `AssetStructure`
 * @param {'edges'|'intrinsic'} bucket
 * @returns {{bucket: string, pathSegments: string[], containerSegments: string[], relativePath: string}}
 *
 * @example
 * decomposePath('edges.hasCxt.Context', 'edges');
 * // { bucket:'edges', pathSegments:['edges','hasCxt','Context'],
 * //   containerSegments:['edges','hasCxt'], relativePath:'hasCxt.Context' }
 * decomposePath('AssetStructure', 'intrinsic');
 * // { bucket:'intrinsic', pathSegments:['AssetStructure'],
 * //   containerSegments:[], relativePath:'AssetStructure' }
 */
const decomposePath = (path, bucket) => {
    const pathSegments = String(path).split('.');
    return {
        bucket,
        pathSegments,
        containerSegments: pathSegments.slice(0, -1),
        relativePath: bucket === 'edges' && pathSegments[0] === 'edges'
            ? pathSegments.slice(1).join('.')
            : path,
    };
};

/**
 * Cardinality cap for an intrinsic reference, from the JSON Schema. `undefined` means
 * uncapped. Edge-bucket paths (`edges.*`) are not schema properties and are always
 * uncapped, so they simply miss the index.
 */
const maxItemsFor = (domain, path) => maxItemsIndex.get(`${domain}:${path}`);

const computePath = (placement, pred, range, group, def) => {
    if (placement === 'edges') return `edges.${pred}.${range}`;
    if (group.path) return group.path;
    if (def.path) return def.path;
    const template = group.pathTemplate || def.pathTemplate;
    if (template) return template.replace('{predicate}', pred).replace('{range}', range);
    return pred;
};

/**
 * @param {Object} edgeDefinitions - The published edge definitions. No default: a caller must
 * name its subject, so nothing can reach a table built from something it did not ask for.
 * @returns {{ table: Object, collisions: Array<string> }} The generated per-entity
 * edgeTable plus any same-key collisions detected during expansion.
 */
export function buildEdgeTable(edgeDefinitions) {
    const table = {};
    const collisions = [];

    const ensure = (entity) => {
        table[entity] = table[entity] || { intrinsic: {}, edges: {}, cxtEdges: {} };
        return table[entity];
    };

    const add = (entity, partition, key, entry) => {
        const part = ensure(entity)[partition];
        if (part[key]) {
            collisions.push(`${entity}.${partition}.${key} (${part[key].path} vs ${entry.path})`);
        }
        part[key] = entry;
    };

    for (const [pred, def] of Object.entries(edgeDefinitions)) {
        const rdf = typeof def.rdf === 'function' ? def.rdf : tentativeRdf;

        for (const group of def.connects) {
            // Placement belongs to the pairing. One verb reaches some ranges through `edges.<verb>.*`
            // and others through a named property — `has` does both — so the group states it where it
            // differs from the predicate's usual one, exactly as it states a path.
            const placement = group.placement || def.placement || 'edges';
            const partition = placement === 'edges' ? 'edges' : 'intrinsic';
            const groupInverse = Object.hasOwn(group, 'inverse') ? group.inverse : def.inverse;
            const template = group.pathTemplate || def.pathTemplate;
            const inversePath = (domain) => resolveInversePath(edgeDefinitions, groupInverse, domain);

            if (pathDependsOnRange(placement, template)) {
                // one entry per (domain, range), keyed by the range/target type
                group.domain.forEach((domain) => group.range.forEach((range) => {
                    const path = computePath(placement, pred, range, group, def);
                    add(domain, partition, path, {
                        predicate: def.predicate,
                        allowed: [range],
                        path,
                        type: STORAGE_TYPE,
                        maxItems: maxItemsFor(domain, path),
                        ...decomposePath(path, partition),
                        inverseEdge: inverseEdgeOf(inversePath(domain)),
                        omcPredicate: rdf({ domain, predicate: pred, range }),
                    });
                }));
            } else {
                // constant path: one entry per domain, allowed = the whole group range
                group.domain.forEach((domain) => {
                    const path = computePath(placement, pred, group.range[0], group, def);
                    add(domain, partition, path, {
                        predicate: def.predicate,
                        allowed: [...group.range],
                        path,
                        type: STORAGE_TYPE,
                        maxItems: maxItemsFor(domain, path),
                        ...decomposePath(path, partition),
                        inverseEdge: inverseEdgeOf(inversePath(domain)),
                        omcPredicate: rdf({ domain, predicate: pred, range: group.range[0] }),
                    });
                });
            }
        }
    }

    // ---- Second pass: Context-mediated cxtEdges, per subject A ----
    // cxtEdges[A] = the back-edge (C --cxtFor--> A) plus A's forward relational
    // edges re-homed on the Context, each with its inverse re-pointed at the
    // Context (right-side inheritance):  (C) --P--> B  and  (B) --inv(P)--> C.
    // The context-attachment edges (hasCxt/cxtFor) are not themselves inherited.
    const CONTEXT = 'Context';
    const cxtForRdf = typeof edgeDefinitions.cxtFor?.rdf === 'function'
        ? edgeDefinitions.cxtFor.rdf
        : tentativeRdf;
    const predicateOf = (path) => (path.startsWith('edges.') ? path.split('.')[1] : null);
    const repointInverse = (inverse) => {
        if (!inverse || !inverse.startsWith('edges.')) return inverse; // null or intrinsic — unchanged
        const parts = inverse.split('.');
        parts[parts.length - 1] = CONTEXT;
        return parts.join('.');
    };

    Object.keys(table).forEach((subject) => {
        // Only subjects that can carry a Context (the domains of hasCxt) get a projection
        if (!table[subject].edges[`edges.hasCxt.${CONTEXT}`]) return;
        const cxt = table[subject].cxtEdges;

        // Left back-edge: the Context refers back to its subject
        cxt[`edges.cxtFor.${subject}`] = {
            predicate: 'cxtFor',
            allowed: [subject],
            path: `edges.cxtFor.${subject}`,
            type: 'array',
            maxItems: undefined,
            ...decomposePath(`edges.cxtFor.${subject}`, 'edges'),
            inverseEdge: inverseEdgeOf(`edges.hasCxt.${CONTEXT}`),
            omcPredicate: cxtForRdf({ domain: CONTEXT, predicate: 'cxtFor', range: subject }),
        };

        // Right-side inheritance: A's forward relational edges, re-homed on the
        // Context with the inverse re-pointed at the Context
        Object.values(table[subject].edges).forEach((edge) => {
            const pred = predicateOf(edge.path);
            if (pred === 'hasCxt' || pred === 'cxtFor') return;
            cxt[edge.path] = {
                predicate: edge.predicate,
                allowed: [...edge.allowed],
                path: edge.path,
                type: edge.type,
                maxItems: edge.maxItems,
                ...decomposePath(edge.path, edge.bucket),
                inverseEdge: inverseEdgeOf(repointInverse(edge.inverse)),
                omcPredicate: edge.omcPredicate,
            };
        });
    });

    // ---- Third pass: resolve each inverse against the table it points into ----
    // `resolveInversePath` works from the inverse's NAME, so where an intrinsic predicate takes its
    // path from a group — `Has` writing `AssetStructure` on an Asset and `Location` on a
    // ParticipantStructure — the name is all it can offer and the path comes back as the predicate.
    // The built table knows better: the reverse of an edge is a row on the TARGET that admits this
    // domain. Resolving against it turns a guess into the place the reference is actually written,
    // and is the only way to reach the cap on that slot, which is a fact about the target's row.
    //
    // Two ways to find it, in order. By path, where the name-derived path already names a real row
    // — the common case, and the one that supplies a cap the first pass could not know. Then by
    // predicate, which is what repairs a guess: `Has` where the answer is
    // `assetStructureProperties.assetGroup.Member`. The predicate comparison folds case, because
    // the two halves spell the same predicate differently by design — an intrinsic path is named
    // by the capitalised property (`RealizationOf`) and a row's `predicate` by the verb
    // (`realizationOf`). Compared verbatim, every intrinsic inverse missed.
    const fold = (term) => String(term).toLowerCase();
    const rowsOn = (target) => ['intrinsic', 'edges']
        .flatMap((part) => Object.values(table[target]?.[part] || {}));

    Object.entries(table).forEach(([domain, partitions]) => {
        PARTITION_NAMES.forEach((partition) => {
            Object.values(partitions[partition] || {}).forEach((entry) => {
                const { path: guessedPath, predicate: name } = entry.inverseEdge ?? {};
                if (!name) return;
                const targets = entry.allowed || [];
                const byPath = targets.reduce((hit, target) => hit
                    || rowsOn(target).find((candidate) => candidate.path === guessedPath), null);
                const byPredicate = byPath || targets.reduce((hit, target) => hit
                    || rowsOn(target).find((candidate) => fold(candidate.predicate) === fold(name)
                        && (candidate.allowed || []).includes(domain)), null);
                if (!byPredicate) return;
                entry.inverseEdge = inverseEdgeOf(byPredicate.path, byPredicate.maxItems);
            });
        });
    });

    return { table, collisions };
}
