/**
 * Generate the Markdown API reference in docs/api/.
 *
 * One file per @module, plus types.md for the OMC typedef namespace and a
 * generated README.md index. Replaces the old docdash HTML site.
 *
 * Run with: npm run docs
 */

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import jsdoc2md from 'jsdoc-to-markdown';

const OUT_DIR = join('docs', 'api');

/** Namespaces documented as their own page, in the order they appear in the index. */
const NAMESPACES = [
    { name: 'OMC', file: 'types.md', title: 'Types', blurb: 'OMC-JSON type definitions' },
    { name: 'OmcUtil', file: 'library.md', title: 'Library', blurb: 'The library namespace' },
];

/** Passed to jsdoc — `access: all` matches the access level the old HTML build used (`-a all`). */
const jsdocOptions = {
    'configure': 'jsdoc2md.json',
    'recurse': true,
    'access': 'all',
    'no-cache': true,
};

/** Passed to dmd. `EOL: posix` keeps reruns byte-identical across platforms. */
const dmdOptions = {
    'heading-depth': 1,
    'param-list-format': 'table',
    'module-index-format': 'none',
    'global-index-format': 'none',
    'separators': true,
    'EOL': 'posix',
};

/**
 * A one-line summary of a description, for the index table.
 *
 * Cuts at the first paragraph before looking for a sentence end — without that, a first paragraph
 * that has no closing full stop runs into the second and the whole description lands in one cell.
 * jsdoc separates description lines with a bare CR, so line endings are normalised first.
 */
function summarize(text = '') {
    const [firstParagraph] = text.replace(/\r\n?/g, '\n').split(/\n[ \t]*\n/);
    const flat = firstParagraph
        .replace(/\s+/g, ' ')
        .replace(/\|/g, '\\|') // a bare pipe would break out of the table cell
        .trim();
    const end = flat.search(/\.(\s|$)/);
    return end === -1 ? flat : flat.slice(0, end + 1);
}

// jsdoc turns a documented `export default` in a file with no @module tag into a `module.exports`
// doclet that dmd has nowhere to put — it just warns "Module tag required in this file" once per
// render call. Drop them: there are two (v2-8tov3-0.js, v2-8/participant/Service.js) and both are
// internal.
const data = (await jsdoc2md.getTemplateData(jsdocOptions))
    .filter((doclet) => doclet.longname !== 'module.exports');

// --- Step 1: Start from a clean directory so a renamed module leaves no orphan file ---
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const write = (file, markdown) => {
    writeFileSync(join(OUT_DIR, file), `${markdown.trim()}\n`, 'utf8');
};

// --- Step 2: One file per module ---
const modules = data
    .filter((doclet) => doclet.kind === 'module')
    .sort((a, b) => a.name.localeCompare(b.name));

for (const module of modules) {
    const template = `{{#module name="${module.name}"}}{{>docs}}{{/module}}`;

    write(`${module.name}.md`, await jsdoc2md.render({ data, template, ...dmdOptions }));
}

// --- Step 3: One file per documented namespace ---
const namespaces = [];
for (const ns of NAMESPACES) {
    if (!data.some((doclet) => doclet.kind === 'namespace' && doclet.name === ns.name)) continue;
    const template = `{{#namespace name="${ns.name}"}}{{>docs}}{{/namespace}}`;

    write(ns.file, await jsdoc2md.render({ data, template, ...dmdOptions }));
    namespaces.push(ns);
}

// --- Step 4: Everything in a file that carries no @module tag (the old site's "Global" page) ---
// dmd counts a global @namespace as a global, so OMC and OmcUtil have to be filtered out by hand
// or this page repeats types.md and library.md in full.
const nsNames = new Set(namespaces.map((ns) => ns.name));
const inNamespace = (scope) => [...nsNames].some((n) => scope === n || scope.startsWith(`${n}.`));
const globalData = data.filter((doclet) => {
    if (doclet.kind === 'namespace' && nsNames.has(doclet.name)) return false;
    return !inNamespace(doclet.memberof || '');
});
const globals = await jsdoc2md.render({
    data: globalData,
    template: '{{#globals}}{{>docs}}{{/globals}}',
    ...dmdOptions,
});
const hasGlobals = Boolean(globals.trim());
if (hasGlobals) write('globals.md', globals);

// --- Step 5: Index, built from the same data so it cannot drift from the files ---
const rows = [
    ...modules.map((m) => `| [${m.name}](./${m.name}.md) | ${summarize(m.description)} |`),
    ...namespaces.map((ns) => `| [${ns.title}](./${ns.file}) | ${ns.blurb} |`),
    ...(hasGlobals ? ['| [Globals](./globals.md) | Members declared outside any module |'] : []),
];

write('README.md', [
    '# omc-util API reference',
    '',
    '<!-- Generated by `npm run docs` — do not edit by hand. -->',
    '',
    '| Module | Description |',
    '| --- | --- |',
    ...rows,
].join('\n'));

// --- Step 6: Report anything that landed in no file ---
const documented = new Set(namespaces.map((ns) => ns.name));
const orphans = data.filter((doclet) => {
    if (doclet.kind === 'module') return false;
    if (doclet.kind === 'namespace' && documented.has(doclet.name)) return false;
    if (doclet.scope === 'inner') return false; // dmd never renders inner identifiers
    const scope = doclet.memberof || '';
    if (!scope) return !hasGlobals;
    if (scope.startsWith('module:')) return false;
    return ![...documented].some((name) => scope === name || scope.startsWith(`${name}.`));
});

console.log(`Wrote ${modules.length} module(s) + ${namespaces.length} namespace(s) to ${OUT_DIR}`);
if (orphans.length) {
    console.log(`\n${orphans.length} doclet(s) belong to no page and were NOT written:`);
    orphans.forEach((doclet) => console.log(`  ${doclet.kind} ${doclet.longname}`));
}
