/**
 * Dumps the schema-derived template shape for BOTH schemas so they can be reviewed by
 * hand and diffed as the LinkML schema converges on the current v3.0 one.
 *
 * Writes into test/omc-v3-0/derived/:
 *   v3-0.json    — everything the engine derives from the current schema
 *   linkml.json  — the same, derived from the LinkML schema (same code path)
 *   diff.md      — a precomputed comparison: entity/reference deltas, a per-entity
 *                  leaf-count table, and the exact differing property paths per entity
 *
 * The per-entity shape is the single unified object: cardinality is carried inline on
 * each array node as `$maxItems` (the codebase's term for the cap, what consumers read),
 * NOT as a separate index. Each file contains only what a validation schema asserts
 * (entity list, property shapes with inline cardinality, reference shape, required
 * fields) — NOT the hand-authored editorial overlay (presentation/idPrefix/group/edges),
 * which is identical across schemas and would only add noise. Keys are sorted deeply so
 * an external diff tool lines the two files up cleanly.
 *
 *   Usage: node test/omc-v3-0/deriveDump.js
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import linkml from '../../src/omc/validation/schema/linkml_omc_schema.schema.json' with { type: 'json' };
import gold from '../../src/omc/validation/schema/OMC-JSON-v3.0.schema.json' with { type: 'json' };
import {
    listEntities, entityShape, referenceShape,
} from '../../src/templates/schemaDerive.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'derived');
mkdirSync(outDir, { recursive: true });

// Recursively sort object keys so JSON.stringify is stable regardless of insertion order.
const sortDeep = (value) => {
    if (Array.isArray(value)) return value.map(sortDeep);
    if (value && typeof value === 'object') {
        return Object.keys(value).sort().reduce((obj, key) => {
            obj[key] = sortDeep(value[key]);
            return obj;
        }, {});
    }
    return value;
};

/** The full derived shape for one schema, deterministically ordered. */
const derive = (schema, label) => {
    const entityMap = listEntities(schema);
    const entityTypes = [...entityMap.keys()].sort();
    const entities = entityTypes.reduce((obj, e) => {
        obj[e] = sortDeep(entityShape(schema, entityMap.get(e)));
        return obj;
    }, {});
    return {
        schema: label,
        schemaId: schema.$id || null,
        referenceShape: sortDeep(referenceShape(schema)),
        entities,
    };
};

// Flatten a derived shape to `path -> signature` leaves. The signature carries everything
// inline on the node — type, cardinality (`max N`), default (`=value`), and requiredness
// (`[required]`) — so a single comparison covers all of them at once. Arrays descend
// through $items at the same path.
const signature = (node) => {
    let sig = node.$type;
    if (typeof node.$maxItems === 'number') sig += ` (max ${node.$maxItems})`;
    if (node.$default !== undefined) sig += ` =${JSON.stringify(node.$default)}`;
    if (Array.isArray(node.$controlledValues)) sig += ` cv{${node.$controlledValues.join('|')}}`;
    if (node.$required) sig += ' [required]';
    return sig;
};
const leafMap = (shape, path = '', out = {}) => {
    if (!shape || typeof shape !== 'object') return out;
    if (typeof shape.$type === 'string') {
        out[path] = signature(shape);
        if (shape.$type === 'array' && shape.$items) leafMap(shape.$items, path, out);
        return out;
    }
    Object.entries(shape).forEach(([k, v]) => {
        if (!k.startsWith('$')) leafMap(v, path ? `${path}.${k}` : k, out);
    });
    return out;
};

const goldDump = derive(gold, 'v3-0');
const linkmlDump = derive(linkml, 'linkml');

writeFileSync(join(outDir, 'v3-0.json'), `${JSON.stringify(goldDump, null, 2)}\n`);
writeFileSync(join(outDir, 'linkml.json'), `${JSON.stringify(linkmlDump, null, 2)}\n`);

// ---- build diff.md ----------------------------------------------------------
const onlyIn = (a, b) => a.filter((x) => !b.includes(x));
const md = [];
md.push('# Derived template diff — v3-0 (gold) vs linkml');
md.push('');
md.push('Schema-derived shape only (no editorial overlay). Generated by `deriveDump.js`.');
md.push('Cardinality is inline in each shape as `$maxItems` and is compared as part of the');
md.push('property signature below — there is no separate cardinality table. These are expected');
md.push('to differ while the LinkML schema is a work in progress; the goal is for this file to');
md.push('shrink toward empty as the two schemas converge.');
md.push('');

// Entities (the entity list is simply the keys of `entities`)
const gEnts = Object.keys(goldDump.entities);
const lEnts = Object.keys(linkmlDump.entities);
md.push('## Entities');
md.push('');
md.push(`- v3-0: ${gEnts.length}   linkml: ${lEnts.length}`);
md.push(`- only in v3-0: ${onlyIn(gEnts, lEnts).join(', ') || '(none)'}`);
md.push(`- only in linkml: ${onlyIn(lEnts, gEnts).join(', ') || '(none)'}`);
md.push('');

// Reference shape (required identifier fields are inline as `$required`)
md.push('## Reference shape');
md.push('');
const refEqual = JSON.stringify(goldDump.referenceShape) === JSON.stringify(linkmlDump.referenceShape);
md.push(refEqual
    ? '- identical in both schemas (required fields marked `$required` inline)'
    : '- DIFFERS between schemas — compare `referenceShape` in the two JSON files');
md.push('');

// Per-entity shape summary table (leaf signature covers type + cardinality)
md.push('## Per-entity shape leaf counts');
md.push('');
md.push('| entity | v3-0 leaves | linkml leaves | only v3-0 | only linkml | shape diff |');
md.push('| --- | ---: | ---: | ---: | ---: | ---: |');
const shared = gEnts.filter((e) => lEnts.includes(e));
const detail = [];
shared.forEach((e) => {
    const g = leafMap(goldDump.entities[e]);
    const l = leafMap(linkmlDump.entities[e]);
    const gKeys = Object.keys(g);
    const lKeys = Object.keys(l);
    const onlyGold = gKeys.filter((p) => !(p in l)).sort();
    const onlyLinkml = lKeys.filter((p) => !(p in g)).sort();
    const sigDiff = gKeys.filter((p) => p in l && g[p] !== l[p]).sort();
    md.push(`| ${e} | ${gKeys.length} | ${lKeys.length} | ${onlyGold.length} | ${onlyLinkml.length} | ${sigDiff.length} |`);
    if (onlyGold.length || onlyLinkml.length || sigDiff.length) {
        detail.push({
            e, onlyGold, onlyLinkml, sigDiff, g, l,
        });
    }
});
md.push('');

// Per-entity detail
md.push('## Per-entity differences (detail)');
md.push('');
md.push('`shape mismatches` are paths present in both but with a different type or cardinality.');
md.push('');
detail.forEach(({
    e, onlyGold, onlyLinkml, sigDiff, g, l,
}) => {
    md.push(`### ${e}`);
    md.push('');
    md.push(`- only in v3-0 (${onlyGold.length}): ${onlyGold.join(', ') || '(none)'}`);
    md.push(`- only in linkml (${onlyLinkml.length}): ${onlyLinkml.join(', ') || '(none)'}`);
    md.push(`- shape mismatches (${sigDiff.length}): ${sigDiff.map((p) => `${p} (${g[p]} vs ${l[p]})`).join(', ') || '(none)'}`);
    md.push('');
});

writeFileSync(join(outDir, 'diff.md'), `${md.join('\n')}\n`);

console.log(`Wrote ${join(outDir, 'v3-0.json')} (${gEnts.length} entities)`);
console.log(`Wrote ${join(outDir, 'linkml.json')} (${lEnts.length} entities)`);
console.log(`Wrote ${join(outDir, 'diff.md')} (${detail.length} entities differ)`);
